### ISSUE TITLE
Calculate the user's average speed in each segment of their tracks

### ISSUE THREAD

**Issue by maianh2611** [rilling/OSMDashboard-Winter-2024-COMP-354#12]
**Description**

This issue aims to compute and save the user's average speed every 5 seconds while recording their track. We will use a timer and calculate the user's distance (i.e., using the start location and end location in a segment) every 5 seconds.

**Expected Outcomes**

The map will display the user's average speed in 5-second segments on their individual tracks.

**Alternative Considered**

We considered computing the user's average speed in distance segments; however, this approach requires us to always keep track of the distance the user has traveled to know when we should compute the average speed. In addition, we also have to keep track of a timer. Therefore, it is more efficient to compute the user's average speed in second segments

**Verification**

Verify whether the average speed in each segment is equal to the distance traveled by the user in that segment divided by the total time taken (i.e., 5 seconds)

**Comment by danbin** [comment]
It's important to highlight that this feature aims for completion by Sprint 3. Additionally, we've incorporated additional components for display, such as "Max Speed" and "Duration of a Run."

**Comment by Abdoul111** [comment]
This feature is completed with success
