### ISSUE TITLE
Implement Runs/Chairlifts table in OSMDashboard

### ISSUE THREAD

**Issue by danbin** [rilling/OSMDashboard-Winter-2024-COMP-354#17]
**Feature Request**
Display accurately Runs and Chairlifts data in a table in the OSMDashboard map

- [x] Display chairlifts information using dummy data (Sprint 1)
- [x] Fetch Runs and Chairlifts data from OpenTracks service functions
- [x] Used the fetched data to display Runs and Chairlifts information in the Runs and Chairlifts table

**Expected Outcome**

-  Runs and Chairlifts data are fetched successfully from OpenTrack

-  Users will see a table containing Runs (i.e., names, average speed, distance, duration, max speed) and Chairlifts (i.e., speed, waiting time, ascent time, distance) information. 

**Alternative Solution**
None

**Verification**

- [x] Verify whether Runs and Chairlifts information is displayed in the table

- [x] Verify whether their values match with the values provided by OpenTrack

**Comment by maianh2611** [comment]
Current status:
 We are successfully displaying chairlift information using dummy data.

Todo: 
Fetch chairlift information from OpenTrack services and accurately display it on the table.

**Comment by maianh2611** [comment]
We created some dummy data for Chairlifts and Runs in OpenTracks so that we could fetch and display that data
