### ISSUE TITLE
Keep Track Width Fixed When Zooming In/Out

### ISSUE THREAD

**Issue by serbancaia** [rilling/OSMDashboard-Winter-2024-COMP-354#19]
**Description**

This issue aims to keep the width of a selected track displayed on the map the same when zooming in or out.

**Expected Outcomes**

This feature should allow the map to show repeated runs recorded on one track as overlapped, which should appear as if there is one wide path plotted on the map for those repeated segments.

**Alternative Considered**

We could merge any part of a path that gets repeated on one track into one plotted part and gradually increase the width of this new merged part for every future repetition on it. However, we would need to set a limit on the width to prevent a path from exceeding a run's borders.

**Verification**

By testing whether the width remains unchanged when zooming in and out. Also by checking whether repeated paths overlap when zooming out and whether they separate when zooming into them.

**Comment by osamahk1** [comment]
Zooming in/out issue has been resolved.
