### ISSUE TITLE
Drawing the lines on the map

### ISSUE THREAD

**Issue by osamahk1** [rilling/OSMDashboard-Winter-2024-COMP-354#21]
Drawing User's Path Lines on Map

Description:
Implement functionality to visually represent the path of the user on the map, enhancing the user experience by providing a visual reference of their skiing journey.

Expected Outcomes:

- Users can visually track their skiing routes in real-time.
- Enhanced user engagement and satisfaction through interactive map visualization.

Alternatives Considered:

- Utilizing GPS data to plot user's path lines.
- Integrating third-party mapping libraries for enhanced visualization.

Verification:

- Verify whether lines have been drawn on the map and are functional for user.
- Conduct user testing to ensure the accuracy and responsiveness of the path lines.

**Comment by maianh2611** [comment]
After examining OSMDashboard's codebase, we found out that these functionalities are provided by OSMDashboard. Therefore, we have decided to close this issue.

**Comment by maianh2611** [comment]
After examining OSMDashboard's codebase, we found out that these functionalities are provided by OSMDashboard. Therefore, we have decided to close this issue.
