### ISSUE TITLE
Display a table with details of the trail 

### ISSUE THREAD

**Issue by ragenpt** [rilling/OSMDashboard-Winter-2024-COMP-354#29]
**Description:** 
Integrate a table display on the screen to showcase comprehensive information about the selected trail such as speed and slope percentage.

**Expected outcome:** 
The details of the highlighted trail are displayed to the user in a table format.

**Alternative solutions:** 
Explore the possibility of presenting trail information through graphs or charts.

**Verification:** 
Verify that upon choosing a specific trail, the correct relevant details of that trail are displayed to the user in a table format.

**Comment by Farnaaaz** [comment]
Duplicate issue 
(done by other groups)
