### ISSUE TITLE
change thickness based on the frequency of traversing the path.

### ISSUE THREAD

**Issue by B-Mousa** [rilling/OSMDashboard-Winter-2024-COMP-354#35]
**Description**

This issue aims to change the thickness of the path according to how many times it has been taken.

**Expected Outcomes**

This feature should allow the map to show the paths in different thicknesses based on how many times the path has been taken. A path should appear thicker than others if it is taken more often. 

**Alternative Considered**

We could display a popup on the corner of the screen that shows how many times the path has been taken when clicking on it

**Verification**

By trying it out by taking the same path multiple times and see if the thickness has changed or not.

**Comment by danbin** [comment]
Regarding this matter, the OSMDashboard has already drawn out the line.
