### ISSUE TITLE
Calculate beginning and ending points of the line for the chairlifts

### ISSUE THREAD

**Issue by BDW12** [rilling/OSMDashboard-Winter-2024-COMP-354#37]
**Description**:
calculate beginning and ending points of the lines that will be drawn on the map for the chairlifts. This will require making use of the data provided by OpenTracks to determine the necessary data
****
**Expected outcome:**
have a clear value for the starting and ending point of the chairlifts in the form of a 2d array

**Alternative solutions:**
we can try to draw the path differently using a different set of functions written in OpenTracks, but that would be so inefficient

**Verification:**
having the above-mentioned functionality written in Java in OSM Dashboard repo

**Comment by Abdoul111** [comment]
We are able to access this information inside MapsActivity inside readTrackPoints() method. This is done!
