### ISSUE TITLE
Compute the average speed and slope for each segments during a run

### ISSUE THREAD

**Issue by danbin** [rilling/OSMDashboard-Winter-2024-COMP-354#40]
***This was not in our initial issues list (in sprint 1). As the project progress, our team founded it useful to add these features for our part (sprint3).

Feature Request:
Allow users to interact directly with the map interface by clicking on a specific segment on the run to view its estimated average speed and the slope. This provides a more intuitive and user-friendly experience.

Expected Outcome:
Upon selecting a segment on the map, users will be presented with real-time estimates of the average speed and slope for that specific segment.

Alternative Solution:
None

Verification:
Verify whether the real-time average speed and slope  for the segment by tracking the user's is accurate in comparison to the estimated waiting of the application.

**Comment by danbin** [comment]
Current Progress:
We've managed to showcase average speed and slope of segments.

To-Do List:
Retrieve information from OpenTrack services and present it accurately within the table interface.

**Comment by maianh2611** [comment]
The OpenTrack services have not been completed by the end of sprint 3
