### ISSUE TITLE
Retrieved information about the start and end of segments from the URI provided by OpenTracks

### ISSUE THREAD

**Issue by maianh2611** [rilling/OSMDashboard-Winter-2024-COMP-354#47]

**Comment by Abdoul111** [comment]
This feature is completed with success. I modified on readTrackPoints() method inside MapsActivity to retrieve this information.

**Comment by Abdoul111** [comment]
closed

**Comment by serbancaia** [comment]
Found how to get the TrackPoint objects representing the start and end points of a segment.
