### ISSUE TITLE
Accurate Distance Calculation Through Snapshots

### ISSUE THREAD

**Issue by dimichoueiry** [rilling/OSMDashboard-Winter-2024-COMP-354#5]
**Description:** 
The software should be designed to capture snapshots every few seconds to facilitate accurate distance calculations for the ski trails.

**Expected Outcome:** 
Distance calculations will be highly accurate due to the frequent snapshots.

**Alternatives Considered:** 
Considered less frequent intervals, but it compromised accuracy.

**Verification:** 
We will verify this feature by comparing the calculated distances with GPS data.

**Comment by ThomasGillard** [comment]
Out of scope
